vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.number = true
vim.opt.splitright = true
vim.opt.termguicolors = true
vim.o.completeopt = "menuone,noselect"
-- opt.wildmode = {"list", "longest"}
